### ISSUE TITLE
MASTUSAID TANZANIA

### ISSUE THREAD

**Issue by careerhub-source** [MASTUSAID/MAST-MOBILE#1]
How to install this app in my mobile phone

**Comment by careerhub-source** [comment]
I need help

**Comment by llsmith05** [comment]
Hi @kiwango - The code here needs to be compiled using Android Studio before it can be installed on your mobile. Are you involved in USAID project in Tanzania? If so, I'd suggest reaching out to someone on that program for instructions. The app won't do anything without their support and access to the MAST server.

**Comment by careerhub-source** [comment]
Thank you for response, current I am not working with that project but I am
very interested with that technology
